tutorial_link: "https://www.railstutorial.org/"
help_link: "https://www.railstutorial.org/help"
book_link: "https://www.railstutorial.org/book"
name: "Mai Minh Quan"
base_title: "Ruby on Rails Tutorial Sample App"
time_format:
  user_history: "%B %d, %Y at %I:%M %p"
digits:
  DIGIT_3: 3
  DIGIT_140: 140
gravatar_email: "http://gravatar.com/emails"
default_from_email: "noreply@example.com"
pagy:
  page_10: 10
image_format: "%w(image/jpeg image/gif image/png)"
image_size: "[500, 500]"
image_type: "image/jpeg,image/gif,image/png"
gravatar_size: 50
max_image_size_mb: 5
