tutorial_link: "https://www.railstutorial.org/"
help_link: "https://www.railstutorial.org/help"
book_link: "https://www.railstutorial.org/book"
name: "Mai Minh Quan"
base_title: "Ruby on Rails Tutorial Sample App"
